DataFrame et series.

A DataFrame is a table.

In [10]:
import pandas as pd
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [11]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [12]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A Series is a single column of a DataFrame. So you can assign row labels to the Series using an **index** parameter. However, a Series **does not have a column name**(headers), it only has one overall **name** :

In [13]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

Reading data

In [2]:
import pandas as pd
df=pd.read_csv('pokemon_data.csv',index_col=0)   #pd.read_csv() function read the data into a DataFrame.
#rq : si on ne met pas index un autre index sera créé
print(df.head()) #par défaut 5 records sinon on met .head(nb)
df.shape #how large the resulting DataFrame (records,columns)

                    Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#
1              Bulbasaur  Grass  Poison  45      49       49       65
2                Ivysaur  Grass  Poison  60      62       63       80
3               Venusaur  Grass  Poison  80      82       83      100
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
#
1       65     45           1      False
2       80     60           1      False
3      100     80           1      False
3      120     80           1      False
4       50     65           1      False

(800, 11)

## Native accessors (by python)

df[**column name**][**n°row**]

In [33]:
df['Name']
df['Name'][1]
df['Name'][0:5]

#
1                Bulbasaur
2                  Ivysaur
3                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

## Indexing in pandas

Pandas has its own accessor operators, **loc** and **iloc**

**Index-based selection : iloc** : selecting data based on its *numerical* position in the data.

           df.iloc[row position][column position]

In [39]:
#read one row
df.iloc[0]
#read one column
df.iloc[:,1]
#read some rows of a column
df.iloc[0:3,1]
#It's also possible to pass a list:
df.iloc[[0,1,2],1]
#last five rows
df.iloc[-5:]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

**Label-based selection : loc** :  it's the data index value, not its position, which matters.

           df.loc[index value][header(column) value]

 <span style="color:red">
 
 **RQ1:**

  df.iloc[] → par **position** (0 = première ligne, 1 = deuxième ligne, …)

df.loc[] → par **étiquette d’index** (la valeur de l’index, qui peut être 0, 1, 2… ou tout autre nombre/texte)</span>

**RQ2:**

iloc -> 0:10 will select entries 0,...,9.

loc  -> So 0:10 will select entries 0,...,10.

In [48]:
df.loc[1:3,'Name']
df.loc[:, ['Name', 'Type 1']]

                      Name   Type 1
#
1                Bulbasaur    Grass
2                  Ivysaur    Grass
3                 Venusaur    Grass
3    VenusaurMega Venusaur    Grass
4               Charmander     Fire
..                     ...      ...
719                Diancie     Rock
719    DiancieMega Diancie     Rock
720    HoopaHoopa Confined  Psychic
720     HoopaHoopa Unbound  Psychic
721              Volcanion     Fire

[800 rows x 2 columns]

## Manipulating the index

definir quelle colonne sera l'index du dataframe

In [52]:
df.set_index("Name")

,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,
Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
Volcanion,Fire,Water,80,110,120,130,90,70,6,True

## Conditional selection

In [54]:
df.loc[df['Type 1']=='Grass']
df.loc[df['Type 1'].isin(['Grass','Rock'])]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
698,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

## Assigning data

Ajouter une nouvelle colonne avec des valeurs pour toutes les lignes

In [56]:
df['colonne-nv']="everyone"
df['colonne-nv']

#
1      everyone
2      everyone
3      everyone
3      everyone
4      everyone
         ...
719    everyone
719    everyone
720    everyone
720    everyone
721    everyone
Name: colonne-nv, Length: 800, dtype: object

In [ ]:
##Read headers
df.columns
##read each column
df['Name'][0:5]
df[['Name','Type 1']][0:5]
##read each row
df.head(4) #4 premiers rows(num 0 1 2 3)
df.iloc[1:4] #num1 jusqu'a num3(1 2 3)
"""for index, row in df.iterrows(): # afficher tous les rows
    print(index,row)"""

"""for index, row in df.iterrows():   #afficher tous les rows de la colonne Name
    print(index,row['Name'])"""

df.loc[df['Type 1']=='Grass'] #afficher les rows correspondant a un type 1=grass
##read a specific case(R,C)
#df.iloc[1,0]

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

# Summary Functions and Maps

### Summary functions

In [7]:
df['Name'].describe()
df['HP'].describe()

count    800.000000
mean      69.258750
std       25.534669
min        1.000000
25%       50.000000
50%       65.000000
75%       80.000000
max      255.000000
Name: HP, dtype: float64

| Ligne     | Signification                                                  |
| --------- | -------------------------------------------------------------- |
| **count** | Le **nombre de valeurs non nulles** (non-NaN) dans la colonne. |
| **mean**  | La **moyenne** des valeurs.                                    |
| **std**   | L’**écart-type**, mesure de dispersion.                        |
| **min**   | La **valeur minimale**.                                        |
| **25%**   | Le **1er quartile** (25 % des valeurs sont inférieures).       |
| **50%**   | La **médiane** (milieu des valeurs).                           |
| **75%**   | Le **3e quartile** (75 % des valeurs sont inférieures).        |
| **max**   | La **valeur maximale**.                                        |
| **unique** | Nombre de valeurs différentes         |
| **top**    | Valeur la plus fréquente (non numérique)             |
| **freq**   | Combien de fois cette valeur apparaît |

In [ ]:
#valeur moyenne
df.HP.mean()

np.float64(69.25875)

In [ ]:
#valeurs distinctes
df['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [ ]:
#le nombre de valeurs distinctes
df['Type 2'].nunique()

18

In [ ]:
#combien de fois chaque valeur répétée apparaît.
df['Type 2'].value_counts()

Type 2
Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ice         14
Rock        14
Water       14
Ghost       14
Fire        12
Electric     6
Normal       4
Bug          3
Name: count, dtype: int64

In [ ]:
#renvoie l’index de la valeur la plus répétée
df['Type 2'].value_counts().idxmax()

'Flying'

Compter le nombre total de valeurs manquantes (NaN) dans tout ton DataFrame training_df.

.isnull()→ Renvoie un DataFrame de booléens (True/False)

In [4]:
import pandas as pd

training_df = pd.DataFrame({
    'A': [1, None, 3],
    'B': [4, 5, None]
})
print(training_df.isnull())

       A      B
0  False  False
1   True  False
2  False   True

.sum() --> compte la somme de chaque colonne avec True= 1 et False= 0.

In [ ]:
training_df.isnull().sum()#nombre total de NaN dans chaque colonne

A    1
B    1
dtype: int64

.sum().sum() --> calcule a nouveau

In [ ]:
training_df.isnull().sum().sum() #nombre total de NaN dans tout le dataframe

np.int64(2)

### Maps

**.map()** permet d’appliquer une opération élément par élément sur une Series (une seule colonne).

In [15]:
HP_mean=df['HP'].mean()
#remean HP values to 0
df['HP'].map(lambda x:x-HP_mean)

#
1     -24.25875
2      -9.25875
3      10.74125
3      10.74125
4     -30.25875
         ...
719   -19.25875
719   -19.25875
720    10.74125
720    10.74125
721    10.74125
Name: HP, Length: 800, dtype: float64

**apply()** is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

In [ ]:
#changer la colonne HP
def remean_points(row):
    row.HP = row.HP - HP_mean
    return row

df.apply(remean_points, axis='columns') #axis='columns' (ou axis=1), il va parcourir chaque ligne une par une
#row est une Serie représentant une ligne.
#à chaque itération, il transforme la ligne en un petit pandas.Series

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,-24.25875,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,-9.25875,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,10.74125,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,10.74125,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,-30.25875,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,-19.25875,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,-19.25875,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,10.74125,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,10.74125,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,10.74125,110,120,130,90,70,6,True

voici un exemple d'une ligne (row) dans une itération  : 

| index | wine | points |
| ----- | ---- | ------ |
| 0     | A    | 90     |

la ligne(row) est transformée en une Serie (après passage par .apply(axis=1)) :

**wine**         A        
**points**      90        
Name:        0             

**Les noms de colonnes** (wine, points) deviennent l’**index** de la Series.

Les valeurs de la ligne ("A", 90) deviennent les valeurs de la Series.

Le numéro de la ligne originale (0) est affiché comme le name de la Series.

row.column_name <=> row.index

**RQ** : 

axis=0 ou "index" → ça parcourt chaque colonne (fonction appliquée colonne par colonne).

axis=1 ou "columns" → ça parcourt chaque ligne (fonction appliquée ligne par ligne).

Note that map() and apply() return new, transformed **Series and DataFrames, respectively.**

**They don't modify the original data they're called on.** If we look at the first row of df, we can see that it still has its original HP value.

#### built-in mapping operations

In [18]:
df['Type 1'] + '-' + df['Type 2']

#
1       Grass-Poison
2       Grass-Poison
3       Grass-Poison
3       Grass-Poison
4                NaN
           ...
719       Rock-Fairy
719       Rock-Fairy
720    Psychic-Ghost
720     Psychic-Dark
721       Fire-Water
Length: 800, dtype: object

In [17]:
df.HP - HP_mean

#
1     -24.25875
2      -9.25875
3      10.74125
3      10.74125
4     -30.25875
         ...
719   -19.25875
719   -19.25875
720    10.74125
720    10.74125
721    10.74125
Name: HP, Length: 800, dtype: float64

In [ ]:
#compter le nombre de case dans colonne HP
df.HP.count()

np.int64(800)

In [30]:
#groupby('nom_colonne') : regrouper les lignes d’un DataFrame par valeur commune dans une ou plusieurs colonnes.
#
grouped=df.groupby('HP')  #count_value() is a shortcut for this

👉 ça ne te donne pas directement un tableau, mais un GroupBy object (un objet de regroupement).
C’est comme dire :

"OK, j’ai trié le DataFrame par les valeurs de la colonne HP, dis-moi maintenant ce que tu veux **faire avec chaque groupe** ?"

In [31]:
for hp_value, group in grouped:
    print(f"HP = {hp_value}")
    print(group)
    print("-"*20)

HP = 1
         Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
292  Shedinja    Bug  Ghost   1      90       45       30       30     40

     Generation  Legendary
#
292           3      False
--------------------
HP = 10
       Name  Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
50  Diglett  Ground    NaN  10      55       25       35       45     95

    Generation  Legendary
#
50           1      False
--------------------
HP = 20
         Name    Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
129  Magikarp     Water    NaN  20      10       55       15       20     80
172     Pichu  Electric    NaN  20      40       15       35       35     60
213   Shuckle       Bug   Rock  20      10      230       10      230      5
349    Feebas     Water    NaN  20      15       20       10       55     80
355   Duskull     Ghost    NaN  20      40       90       30       90     25
439  Mime Jr.   Psychic  Fairy  20      25       45       70       90     60

     Generation  Legendary
#
129           1      False
172           2      False
213           2      False
349           3      False
355           3      False
439           4      False
--------------------
HP = 25
         Name    Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
63       Abra   Psychic    NaN  25      20       15      105       55     90
81  Magnemite  Electric  Steel  25      35       70       95       55     45

    Generation  Legendary
#
63           1      False
81           1      False
--------------------
HP = 28
      Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
280  Ralts  Psychic  Fairy  28      25       25       45       35     40

     Generation  Legendary
#
280           3      False
--------------------
HP = 30
         Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
19    Rattata    Normal      NaN  30      56       35       25       35
90   Shellder     Water      NaN  30      65      100       45       25
92     Gastly     Ghost   Poison  30      35       30      100       35
98     Krabby     Water      NaN  30     105       90       25       25
116    Horsea     Water      NaN  30      40       70       70       25
120    Staryu     Water      NaN  30      45       55       70       55
140    Kabuto      Rock    Water  30      80       90       55       45
191   Sunkern     Grass      NaN  30      30       30       30       30
299  Nosepass      Rock      NaN  30      45      135       45       90
307  Meditite  Fighting  Psychic  30      40       55       40       55
410  Shieldon      Rock    Steel  30      42      118       42       88
415    Combee       Bug   Flying  30      30       42       30       42
543  Venipede       Bug   Poison  30      45       59       30       39

     Speed  Generation  Legendary
#
19      72           1      False
90      40           1      False
92      80           1      False
98      50           1      False
116     60           1      False
120     85           1      False
140     55           1      False
191     30           2      False
299     30           3      False
307     60           3      False
410     30           4      False
415     70           4      False
543     57           5      False
--------------------
HP = 31
        Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
290  Nincada    Bug  Ground  31      45       90       30       30     40

     Generation  Legendary
#
290           3      False
--------------------
HP = 35
          Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
23       Ekans    Poison     NaN  35      60       44       40       54
25     Pikachu  Electric     NaN  35      55       40       50       50
46       Paras       Bug   Grass  35      70       55       45       55
51     Dugtrio    Ground     NaN  35      80       50       50       70
84       Doduo    Normal  Flying  35      85       45       35       35
95        Onix      Rock  Ground  35      45      160       30       45
138    Omanyte      Rock   Water  35      40      100       90       55
161    Sentret    Normal     NaN  35      46       34       35       45
175     Togepi     Fairy     NaN  35      20       65       40       65
187     Hoppip     Grass  Flying  35      35       40       35       55
223   Remoraid     Water     NaN  35      65       35       65       35
236    Tyrogue  Fighting     NaN  35      35       35       35       35
261  Poochyena      Dark     NaN  35      55       35       30       30
366   Clamperl     Water     NaN  35      64       85       74       55
602     Tynamo  Electric     NaN  35      55       40       45       40

     Speed  Generation  Legendary
#
23      55           1      False
25      90           1      False
46      25           1      False
51     120           1      False
84      75           1      False
95      70           1      False
138     35           1      False
161     20           2      False
175     20           2      False
187     50           2      False
223     65           2      False
236     35           2      False
261     35           3      False
366     32           3      False
602     60           5      False
--------------------
HP = 36
          Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
582  Vanillite    Ice    NaN  36      50       50       65       60     44

     Generation  Legendary
#
582           5      False
--------------------
HP = 37
          Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
401  Kricketot    Bug    NaN  37      25       41       25       41     25

     Generation  Legendary
#
401           4      False
--------------------
HP = 38
           Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
37       Vulpix     Fire    NaN  38      41       40       50       65     65
263   Zigzagoon   Normal    NaN  38      30       41       30       41     60
281      Kirlia  Psychic  Fairy  38      35       35       65       55     50
562      Yamask    Ghost    NaN  38      30       85       55       65     30
659    Bunnelby   Normal    NaN  38      36       38       32       36     57
664  Scatterbug      Bug    NaN  38      35       40       27       25     35

     Generation  Legendary
#
37            1      False
263           3      False
281           3      False
562           5      False
659           6      False
664           6      False
--------------------
HP = 39
           Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
4    Charmander   Fire    NaN  39      52       43       60       50     65
155   Cyndaquil   Fire    NaN  39      52       43       60       50     65

     Generation  Legendary
#
4             1      False
155           2      False
--------------------
HP = 40
           Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
13       Weedle       Bug   Poison  40      35       30       20       20
16       Pidgey    Normal   Flying  40      45       40       35       35
21      Spearow    Normal   Flying  40      60       30       31       31
41        Zubat    Poison   Flying  40      45       35       30       40
52       Meowth    Normal      NaN  40      45       35       40       40
56       Mankey  Fighting      NaN  40      80       35       35       45
60      Poliwag     Water      NaN  40      50       40       40       40
64      Kadabra   Psychic      NaN  40      35       30      120       70
72    Tentacool     Water   Poison  40      40       35       50      100
74      Geodude      Rock   Ground  40      80      100       30       30
100     Voltorb  Electric      NaN  40      30       50       55       55
109     Koffing    Poison      NaN  40      65       95       60       45
122    Mr. Mime   Psychic    Fairy  40      45       65      100      120
165      Ledyba       Bug   Flying  40      20       30       40       80
167    Spinarak       Bug   Poison  40      60       40       40       40
177        Natu   Psychic   Flying  40      50       45       70       45
218      Slugma      Fire      NaN  40      40       40       70       40
252     Treecko     Grass      NaN  40      45       35       65       55
270       Lotad     Water    Grass  40      30       30       40       50
273      Seedot     Grass      NaN  40      40       50       30       30
276     Taillow    Normal   Flying  40      55       30       30       30
278     Wingull     Water   Flying  40      30       30       55       30
283     Surskit       Bug    Water  40      30       32       50       52
309   Electrike  Electric      NaN  40      45       40       65       40
343      Baltoy    Ground  Psychic  40      40       55       40       70
356    Dusclops     Ghost      NaN  40      70      130       60      130
374      Beldum     Steel  Psychic  40      55       80       35       60
396      Starly    Normal   Flying  40      55       30       30       30
406       Budew     Grass   Poison  40      30       35       50       70
412       Burmy       Bug      NaN  40      29       45       29       45
447       Riolu  Fighting      NaN  40      70       40       35       40
451     Skorupi    Poison      Bug  40      50       90       30       55
544  Whirlipede       Bug   Poison  40      55       99       40       79
546    Cottonee     Grass    Fairy  40      27       60       37       50
570       Zorua      Dark      NaN  40      65       40       80       40
599       Klink     Steel      NaN  40      55       70       45       60
653    Fennekin      Fire      NaN  40      45       40       62       60
714      Noibat    Flying   Dragon  40      30       35       45       40

     Speed  Generation  Legendary
#
13      50           1      False
16      56           1      False
21      70           1      False
41      55           1      False
52      90           1      False
56      70           1      False
60      90           1      False
64     105           1      False
72      70           1      False
74      20           1      False
100    100           1      False
109     35           1      False
122     90           1      False
165     55           2      False
167     30           2      False
177     70           2      False
218     20           2      False
252     70           3      False
270     30           3      False
273     30           3      False
276     85           3      False
278     85           3      False
283     65           3      False
309     65           3      False
343     55           3      False
356     25           3      False
374     30           3      False
396     60           4      False
406     55           4      False
412     36           4      False
447     60           4      False
451     65           4      False
544     47           5      False
546     66           5      False
570     65           5      False
599     30           5      False
653     60           6      False
714     55           6      False
--------------------
HP = 41
         Name  Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
147   Dratini  Dragon    NaN  41      64       45       50       50     50
509  Purrloin    Dark    NaN  41      50       37       50       37     66
656   Froakie   Water    NaN  41      56       40       62       44     71

     Generation  Legendary
#
147           1      False
509           5      False
656           6      False
--------------------
HP = 42
        Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
688  Binacle   Rock  Water  42      52       67       39       56     50

     Generation  Legendary
#
688           6      False
--------------------
HP = 43
         Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#
341  Corphish  Water    NaN  43      80       65       50       35     35
370   Luvdisc  Water    NaN  43      30       55       40       65     97
708  Phantump  Ghost  Grass  43      70       48       50       60     38

     Generation  Legendary
#
341           3      False
370           3      False
708           6      False
--------------------
HP = 44
                    Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#
7               Squirtle     Water     NaN  44      48       65       50
353              Shuppet     Ghost     NaN  44      75       35       63
390             Chimchar      Fire     NaN  44      58       44       58
597            Ferroseed     Grass   Steel  44      50       91       24
669              Flabébé     Fairy     NaN  44      38       39       61
694           Helioptile  Electric  Normal  44      38       33       61
710  PumpkabooSmall Size     Ghost   Grass  44      66       70       44

     Sp. Def  Speed  Generation  Legendary
#
7         64     43           1      False
353       33     45           3      False
390       44     61           4      False
597       86     10           5      False
669       79     42           6      False
694       43     70           6      False
710       55     56           6      False
--------------------
HP = 45
           Name    Type 1   Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
1     Bulbasaur     Grass   Poison  45      49       49       65       65
10     Caterpie       Bug      NaN  45      30       35       20       20
14       Kakuna       Bug   Poison  45      25       50       25       25
43       Oddish     Grass   Poison  45      50       55       75       65
93      Haunter     Ghost   Poison  45      50       45      115       55
118     Goldeen     Water      NaN  45      67       60       35       50
152   Chikorita     Grass      NaN  45      49       65       49       65
225    Delibird       Ice   Flying  45      55       45       65       45
228    Houndour      Dark     Fire  45      60       30       80       50
238    Smoochum       Ice  Psychic  45      30       15       85       65
239      Elekid  Electric      NaN  45      63       37       65       55
240       Magby      Fire      NaN  45      75       37       70       55
255     Torchic      Fire      NaN  45      60       40       70       50
265     Wurmple       Bug      NaN  45      45       35       20       30
318    Carvanha     Water     Dark  45      90       20       65       20
328    Trapinch    Ground      NaN  45     100       45       45       45
333      Swablu    Normal   Flying  45      40       60       40       75
347     Anorith      Rock      Bug  45      95       50       40       50
371       Bagon    Dragon      NaN  45      75       60       40       30
403       Shinx  Electric      NaN  45      65       34       40       34
420     Cherubi     Grass      NaN  45      35       45       62       53
433   Chingling   Psychic      NaN  45      30       50       65       50
458     Mantyke     Water   Flying  45      20       50       60      120
477    Dusknoir     Ghost      NaN  45     100      135       65      135
495       Snivy     Grass      NaN  45      45       55       45       55
504      Patrat    Normal      NaN  45      55       39       35       39
506    Lillipup    Normal      NaN  45      60       45       25       45
522     Blitzle  Electric      NaN  45      60       32       50       32
540    Sewaddle       Bug    Grass  45      53       70       40       60
548     Petilil     Grass      NaN  45      35       50       70       50
574     Gothita   Psychic      NaN  45      30       50       55       65
577     Solosis   Psychic      NaN  45      30       40      105       50
619     Mienfoo  Fighting      NaN  45      85       50       55       50
624    Pawniard      Dark    Steel  45      85       70       40       40
661  Fletchling    Normal   Flying  45      50       43       40       38
665      Spewpa       Bug      NaN  45      22       60       27       30
679     Honedge     Steel    Ghost  45      80      100       35       37
704       Goomy    Dragon      NaN  45      50       35       55       75

     Speed  Generation  Legendary
#
1       45           1      False
10      45           1      False
14      35           1      False
43      30           1      False
93      95           1      False
118     63           1      False
152     45           2      False
225     75           2      False
228     65           2      False
238     65           2      False
239     95           2      False
240     83           2      False
255     45           3      False
265     20           3      False
318     65           3      False
328     10           3      False
333     50           3      False
347     75           3      False
371     50           3      False
403     45           4      False
420     35           4      False
433     45           4      False
458     50           4      False
477     45           4      False
495     63           5      False
504     42           5      False
506     55           5      False
522     76           5      False
540     42           5      False
548     30           5      False
574     45           5      False
577     20           5      False
619     65           5      False
624     60           5      False
661     62           6      False
665     29           6      False
679     28           6      False
704     40           6      False
--------------------
HP = 46
               Name  Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
32   Nidoran (Male)  Poison    NaN  46      57       40       40       40
610            Axew  Dragon    NaN  46      87       60       30       40

     Speed  Generation  Legendary
#
32      50           1      False
610     57           5      False
--------------------
HP = 48
         Name   Type 1    Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
#
132     Ditto   Normal       NaN  48      48       48       48       48
201     Unown  Psychic       NaN  48      72       48       72       48
453  Croagunk   Poison  Fighting  48      61       40       61       40

     Speed  Generation  Legendary
#
132     48           1      False
201     48           2      False
453     50           4      False
--------------------
HP = 49
                      Name  Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
#
431                Glameow  Normal    NaN  49      55       42       42
456                Finneon   Water    NaN  49      49       56       49
710  PumpkabooAverage Size   Ghost  Grass  49      66       70       44

     Sp. Def  Speed  Generation  Legendary
#
431       37     85           4      False
456       61     66           4      False
710       55     51           6      False
--------------------
HP = 50
                    Name  Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#
11               Metapod     Bug     NaN  50      20       55       25
27             Sandshrew  Ground     NaN  50      75       85       20
54               Psyduck   Water     NaN  50      52       48       65
69            Bellsprout   Grass  Poison  50      75       35       70
77                Ponyta    Fire     NaN  50      85       55       65
..                   ...     ...     ...  ..     ...      ...      ...
690               Skrelp  Poison   Water  50      60       60       60
692            Clauncher   Water     NaN  50      53       62       58
703              Carbink    Rock   Fairy  50      50      150       50
719              Diancie    Rock   Fairy  50     100      150      100
719  DiancieMega Diancie    Rock   Fairy  50     160      110      160

     Sp. Def  Speed  Generation  Legendary
#
11        25     30           1      False
27        30     40           1      False
54        50     55           1      False
69        30     40           1      False
77        65     90           1      False
..       ...    ...         ...        ...

In [32]:
df.groupby('HP').HP.count()

HP
1      1
10     1
20     6
25     2
28     1
      ..
165    1
170    1
190    1
250    1
255    1
Name: HP, Length: 94, dtype: int64

In [33]:
df.groupby('HP').Attack.min()

HP
1      90
10     55
20     10
25     20
28     25
       ..
165    75
170    90
190    33
250     5
255    10
Name: Attack, Length: 94, dtype: int64

apply n’a pas le même comportement selon qu’on l’utilise sur un DataFrame ou sur un GroupBy !!!!!

1️⃣ DataFrame.apply()

-Quand tu appelles apply directement sur un DataFrame :

df.apply(fonction)


Par défaut axis=0 → donc fonction est appliquée colonne par colonne

Si tu mets axis=1 → fonction est appliquée ligne par ligne

👉 Ici, la fonction reçoit une Series (pas le DataFrame entier) :

axis=0 → chaque colonne devient une Series

axis=1 → chaque ligne devient une Series

2️⃣ GroupBy.apply()

df.groupby("col").apply(fonction)

La fonction reçoit un DataFrame entier correspondant à chaque groupe

Tu n’as pas besoin de mettre axis, car ça s’applique par groupe, pas par ligne/colonne

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "group": ["A", "A", "B", "B"],
    "value": [10, 20, 30, 40]
})
print(df)
print(df.groupby("group").apply(lambda g: g["value"].mean()))
# 15=mean(10,20) et 35=mean(30,40)

  group  value
0     A     10
1     A     20
2     B     30
3     B     40
group
A    15.0
B    35.0
dtype: float64

C:\Users\USER\AppData\Local\Temp\ipykernel_2516\3192480486.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby("group").apply(lambda g: g["value"].mean()))

you can also group by more than one column.

In [5]:
df.groupby(["HP", "Type 1"])

you can also run a bunch of different functions on your sub-DataFrame simultaneously.

In [7]:
df.groupby(["HP"]).HP.agg([len,max,min])

C:\Users\USER\AppData\Local\Temp\ipykernel_2516\2998673307.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(["HP"]).HP.agg([len,max,min])
C:\Users\USER\AppData\Local\Temp\ipykernel_2516\2998673307.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(["HP"]).HP.agg([len,max,min])

     len  max  min
HP
1      1    1    1
10     1   10   10
20     6   20   20
25     2   25   25
28     1   28   28
..   ...  ...  ...
165    1  165  165
170    1  170  170
190    1  190  190
250    1  250  250
255    1  255  255

[94 rows x 3 columns]

## Multi-indexes

In [2]:
print(df.groupby(['Type 1', 'Type 2']).HP.agg([len]))

                 len
Type 1 Type 2
Bug    Electric    2
       Fighting    2
       Fire        2
       Flying     14
       Ghost       1
...              ...
Water  Ice         3
       Poison      3
       Psychic     5
       Rock        4
       Steel       1

[136 rows x 1 columns]

In [ ]:
print(type(df.index))

#reset_index() de pandas sert à réinitialiser l’index
df.reset_index()

<class 'pandas.core.indexes.base.Index'>

### Sorting :
To get data in the order want it in we can sort it ourselves

In [5]:
df.sort_values(by='HP')

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
439,Mime Jr.,Psychic,Fairy,20,25,45,70,90,60,4,False
...,...,...,...,...,...,...,...,...,...,...,...
594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False

In [6]:
#sort from high to low : 
df.sort_values(by='HP', ascending=False)

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...
213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

In [7]:
#sort by index:
df.sort_index()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

##### sorting by multiple columns:

- pandas trie d’abord selon col1.

- Si certaines lignes ont la même valeur dans col1, alors il les trie selon col2.

In [ ]:
df.sort_values(by=['HP', 'Type 1'])

# 5. Data Types and Missing Values

#### Dtype
The data type for a column in a DataFrame or a Series is known as the dtype.

In [ ]:
#dtype : return a column type
df.HP.dtype
df.index.dtype
#dtypes : returns dtype of every column in the DataFrame
df.dtypes

Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

float64 means that it's using a 64-bit floating point number; int64 means a similarly sized integer instead, and so on.

columns consisting entirely of strings do not get their own type; they are  given the object type.

to convert a column of one type into another :

In [10]:
df.HP.astype('float64')

#
1      45.0
2      60.0
3      80.0
3      80.0
4      39.0
       ...
719    50.0
719    50.0
720    80.0
720    80.0
721    80.0
Name: HP, Length: 800, dtype: float64

#### Missing data
Entries missing values are given the value NaN, short for "Not a Number". they are always of the float64 dtype.

In [12]:
#select NaN entries 
df[pd.isnull(df.HP)]
#select the not null entries
df[pd.notnull(df.HP)]
#replace "NaN" with an "Unknown" 
df.HP.fillna("Unknown")
#replace a non null value with another
df.Generation.replace("1","2")

#
1      1
2      1
3      1
3      1
4      1
      ..
719    6
719    6
720    6
720    6
721    6
Name: Generation, Length: 800, dtype: int64

# 6.Renaming and Combining
Oftentimes data will come to us with column names, index names, or other naming conventions that we are not satisfied with. -> how to use pandas functions to change the names of the offending entries to something better.

### Renaming : rename()

In [ ]:
df.rename(columns={"Attack":"attaque"})
df.rename(index={1:"firstEntry", 2:"secondEntry"}) #attention! on met les numeros d'indexes non pas leur valeurs
#set_index() is usually more convenient.

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
firstEntry,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
secondEntry,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
df.rename_axis(index="pokemon n°", columns="attributes")
#ou bien : 
#df.rename_axis("pokemon n°", axis='rows')
#df.rename_axis("attributes", axis='columns')

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
pokemon n°,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Combining
*  concat()

In [26]:
df1 = pd.DataFrame({"A": [1,2], "B": [3,4]})
df2 = pd.DataFrame({"A": [5,6], "B": [7,8]})
print(df1)
print(df2)

   A  B
0  1  3
1  2  4
   A  B
0  5  7
1  6  8

In [27]:
print(pd.concat([df1, df2], axis=0))

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [28]:
print(pd.concat([df1, df2], axis=1))

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

* join() : Join **par index**

In [30]:
df1 = pd.DataFrame({"A": [1,2]}, index=["x","y"])
df2 = pd.DataFrame({"B": [3,4]}, index=["x","z"])
print(df1)
print(df2)

   A
x  1
y  2
   B
x  3
z  4

In [ ]:

print(df1.join(df2, how="left")) #how="left" garde l’index de df1 , how="right" garde l'index de df2

   A    B
x  1  3.0
y  2  NaN

In [34]:
print(df1.join(df2, how="outer")) #union des deux indexes

     A    B
x  1.0  3.0
y  2.0  NaN
z  NaN  4.0

In [ ]:
#si les deux dfs ont meme header
df1 = pd.DataFrame({"A": [1, 2]}, index=["x", "y"])
df2 = pd.DataFrame({"A": [3, 4]}, index=["x", "y"])
print(df1.join(df2, lsuffix="_left", rsuffix="_right"))
#Si les colonnes ont le même nom → on doit mettre des suffixes pour éviter le conflit.

   A_left  A_right
x       1        3
y       2        4